### ISSUE TITLE
Connect Hakai CTD Profile Datasets to the Hakai Database

### ISSUE THREAD

**Issue by JessyBarrette** [HakaiInstitute/hakai-datasets#122]
# Context
The automated qc of the CTD data will make it soon in production and will make possible to present the hakai ctd data directely from the hakai database. In order to proceed the following steps needs to be executed:

- [x] Add QARTOD tests available on hakai database (see https://github.com/HakaiInstitute/hakai-profile-qaqc/issues/12)
- [x] Run QARTOD tests from cron job (see https://github.com/HakaiInstitute/hakai-profile-qaqc/issues/12)
- [x] Make `ctd.ctd_post_qc_data` available on hakai db 
- [x] Deploy erddap related view/table within the erddap schema #121 
- [x] Handle the QARTOD data type associated with the level_1 variables. ERDDAP doesn't handle directly those it seems. #123 
- [x] Test on development erddap
- [x] Merge to production
- [x] Confirm all is working as expected on production
- [x] Completed

**Comment by JessyBarrette** [comment]
Hakai CTD data QC is now fully automated and available on ERDDAP
